- AnaliseProjeto/CuidaPet.mdj
Foi adicionada a **entidade** **VacinaPet** que possui atributos que representam a data da vacina e o lote.
Na **entidade** **pedido** foi adicionado o atributo quantidade.
> Corrigir diagrama e entidade

- AnaliseProjeto/CuidaPet.mdj
Retira entidade "estabelecimento"
Estabelece relacionamento entre entidade "produto" e entidade "categoria"
> Corrige o BCE do caso de uso "Manter Produtos"

- AnaliseProjeto/CuidaPet.mdj
No diagrama BCE "manter pets" foram adicionadas as relações de pets entre espécie, raça e doença
> add relações Espécie, Raça e Doença

- AnaliseProjeto/CuidaPet.mdj
Feito as solicitações da issue e adicionado as entidades espécie e doença, pois o ator manipula-as diretamente.
> refact: BCE caso de uso Manter Vacina Close #68

- AnaliseProjeto/CuidaPet.mdj
Baseado no analysis model, todas as classes entity collection, no design model, são mapeadas para context e retirados os esteriótipos
> mapeia para context o que de entity collection

- Codigo/Core/Core.csproj
- Codigo/Core/DTO/ProdutoDto.cs
- Codigo/Core/Service/IProdutoService.cs
- Codigo/Core/Service/ServiceException.cs
- Codigo/CuidaPetWeb/Controllers/ProdutoController.cs
- Codigo/CuidaPetWeb/CuidaPetWeb.csproj
- Codigo/CuidaPetWeb/Filter/CustomExceptionFilter.cs
- Codigo/CuidaPetWeb/Mappers/ProdutoProfile.cs
- Codigo/CuidaPetWeb/Models/ProdutoViewModel.cs
- Codigo/CuidaPetWeb/Program.cs
- Codigo/CuidaPetWeb/Views/Produto/Create.cshtml
- Codigo/CuidaPetWeb/Views/Produto/Delete.cshtml
- Codigo/CuidaPetWeb/Views/Produto/Details.cshtml
- Codigo/CuidaPetWeb/Views/Produto/Edit.cshtml
- Codigo/CuidaPetWeb/Views/Produto/Index.cshtml
- Codigo/CuidaPetWeb/Views/Shared/Error.cshtml
- Codigo/CuidaPetWeb/Views/Shared/_Layout.cshtml
- Codigo/Service/ProdutoService.cs
- Codigo/Service/Service.csproj
- CRUD de "ManterProdutos" ✅
- Implementado da classe para validação de regras de negócio (ServiceException)✅
- Implementado filtro de exceção personalizado.✅
> Fazer CRUD para o caso de uso "Manter Produtos"

- Codigo/CuidaPetWeb/Controllers/EspecieController.cs
- Codigo/CuidaPetWeb/Views/Shared/_Layout.cshtml
add: Link para espécies no _Layout
Close #133
> fix: remover checagens no controller. Close #133

- Codigo/CuidaPet.sln
- Codigo/CuidaPetWeb/Controllers/ProdutoController.cs
- Codigo/CuidaPetWebTests/Controllers/ProdutoControllerTests.cs
- Codigo/CuidaPetWebTests/CuidaPetWebTests.csproj
- Codigo/Service/ProdutoService.cs
- Codigo/ServiceTests/ProdutoServiceTests.cs
- Codigo/ServiceTests/ServiceTests.csproj
Testes da controller ✅
Testes da service✅
> Criar testes automáticos para o caso de uso "Manter Produtos"

- Codigo/CuidaPetWebTests/Controllers/RacaControllerTests.cs
- Codigo/ServiceTests/RacaServiceTests.cs
Implementado os testes da controller e da service do caso de uso "Manter Raças"
> add: testes automatizados do crud "Manter Raças" close #130

- Codigo/ServiceTests/DoencaServiceTests.cs
desenvolvido conforme padronização os testes para as Doenças
> Testes para a controller e service de Doencas adicionados.

- Codigo/Core/Especie.cs
- Codigo/CuidaPetWeb/Controllers/EspecieController.cs
- Codigo/CuidaPetWeb/Models/EspecieViewModel.cs
- Codigo/CuidaPetWeb/Views/Especie/Create.cshtml
- Codigo/CuidaPetWeb/Views/Especie/Index.cshtml
- Codigo/CuidaPetWeb/Views/Shared/_Layout.cshtml
- Codigo/CuidaPetWeb/wwwroot/css/site.css
- Codigo/CuidaPetWeb/wwwroot/js/site.js
- Codigo/CuidaPetWebTests/Controllers/EspecieControllerTests.cs
> Add Views de Create e Index da Especie. Close #140

- Codigo/Core/Especie.cs
- Codigo/CuidaPetWeb/Models/EspecieViewModel.cs
- Codigo/ServiceTests/VacinaServiceTests.cs
- Além da criação dos testes, corrige um erro de padronização de código relacionado a entidade espécie
> Cria os testes de integração da VacinaService

- Codigo/Core/Service/IDoencaService.cs
- Codigo/Core/Service/IEspecieService.cs
- Codigo/Core/Service/IProdutoService.cs
- Codigo/Core/Service/IRacaService.cs
- Codigo/Core/Service/IVacinaService.cs
- Codigo/CuidaPetWeb/Controllers/DoencaController.cs
- Codigo/CuidaPetWeb/Controllers/EspecieController.cs
- Codigo/CuidaPetWeb/Controllers/ProdutoController.cs
- Codigo/CuidaPetWeb/Controllers/RacaController.cs
- Codigo/CuidaPetWeb/Controllers/VacinaController.cs
- Codigo/CuidaPetWeb/Views/Doenca/Index.cshtml
- Codigo/CuidaPetWeb/Views/Especie/Index.cshtml
- Codigo/CuidaPetWeb/Views/Produto/Index.cshtml
- Codigo/CuidaPetWeb/Views/Raca/Index.cshtml
- Codigo/CuidaPetWeb/Views/Shared/_Layout.cshtml
- Codigo/CuidaPetWeb/Views/Vacina/Index.cshtml
- Codigo/CuidaPetWeb/wwwroot/css/site.css
- Codigo/Service/DoencaService.cs
- Codigo/Service/EspecieService.cs
- Codigo/Service/ProdutoService.cs
- Codigo/Service/RacaService.cs
- Codigo/Service/VacinaService.cs
A paginação foi adicionada para todas as tabelas que foram criadas até o momento: Raça, Espécie, Produto, Doença e Vacina
> Adiciona a paginação nas tabelas das views

- Codigo/Core/Service/IFuncionarioService.cs
- Codigo/CuidaPet.sln
- Codigo/CuidaPetWeb/Controllers/FuncionarioController.cs
- Codigo/CuidaPetWeb/CuidaPetWeb.csproj
- Codigo/CuidaPetWeb/Mappers/FuncionarioProfile.cs
- Codigo/CuidaPetWeb/Models/FuncionarioViewModel.cs
- Codigo/CuidaPetWeb/Program.cs
- Codigo/CuidaPetWeb/Views/Funcionario/Create.cshtml
- Codigo/CuidaPetWeb/Views/Funcionario/Delete.cshtml
- Codigo/CuidaPetWeb/Views/Funcionario/Details.cshtml
- Codigo/CuidaPetWeb/Views/Funcionario/Edit.cshtml
- Codigo/CuidaPetWeb/Views/Funcionario/Index.cshtml
- Codigo/Service/FuncionarioService.cs
- Codigo/Util/CPFAttribute.cs
- Codigo/Util/Methods.cs
- Codigo/Util/Util.csproj
Implementado:
- ViewModel
- Controller
- Interface e Service
- Views (De acordo com o design system do projeto atual)
- Projeto "Util" para métodos de validação personalizada e atributos de validação.
> Fazer CRUD para o caso de uso "Manter Funcionários"

- Codigo/Core/DTO/PessoaDto.cs
- Codigo/Core/Service/IPessoaService.cs
- Codigo/CuidaPetWeb/Controllers/PessoaController.cs
- Codigo/CuidaPetWeb/Mappers/PessoaProfile.cs
- Codigo/CuidaPetWeb/Models/PessoaViewModel.cs
- Codigo/CuidaPetWeb/Program.cs
- Codigo/CuidaPetWeb/Views/Pessoa/Create.cshtml
- Codigo/CuidaPetWeb/Views/Pessoa/Delete.cshtml
- Codigo/CuidaPetWeb/Views/Pessoa/Details.cshtml
- Codigo/CuidaPetWeb/Views/Pessoa/Edit.cshtml
- Codigo/CuidaPetWeb/Views/Pessoa/Index.cshtml
- Codigo/CuidaPetWeb/Views/Shared/_Layout.cshtml
- Codigo/Service/PessoaService.cs
obs: CPF está na entidade Funcionario. Necessário alterar para a entidade Pessoa, já que a pessoa terá um CPF independente de ser funcionário.
> Feito cadastro do tutor

- Codigo/CuidaPetWebTests/Controllers/PetControllerTests.cs
- Codigo/ServiceTests/PetServiceTests.cs
Feito os testes automáticos do caso de uso
> add: testes automáticos do caso de uso "Manter Pets"

- Codigo/Core/DTO/EspecialidadeDto.cs
- Codigo/Core/Service/IEspecialidadeService.cs
- Codigo/CuidaPetWeb/Controllers/EspecialidadeController.cs
- Codigo/CuidaPetWeb/Mappers/EspecialidadeProfile.cs
- Codigo/CuidaPetWeb/Models/EspecialidadeViewModel.cs
- Codigo/CuidaPetWeb/Program.cs
- Codigo/CuidaPetWeb/Views/Especialidade/Create.cshtml
- Codigo/CuidaPetWeb/Views/Especialidade/Delete.cshtml
- Codigo/CuidaPetWeb/Views/Especialidade/Details.cshtml
- Codigo/CuidaPetWeb/Views/Especialidade/Edit.cshtml
- Codigo/CuidaPetWeb/Views/Especialidade/Index.cshtml
- Codigo/CuidaPetWeb/Views/Shared/_Layout.cshtml
- Codigo/Service/EspecialidadeService.cs
Novas adições ao projeto:
Core -> DTO -> `EspecialidadeDto.cs`
Core -> Service -> `IEspecialidadeService.cs`
CuidaPetWeb -> Controllers -> `EspecialidadeController.cs`
CuidaPetWeb -> Mappers-> `EspecialidadeProfile.cs`
CuidaPetWeb -> Models-> `EspecialidadeViewModel.cs`
CuidaPetWeb -> Views -> `Especialidade` -> `Index.cs`
CuidaPetWeb -> Views -> `Especialidade` -> `Create.cs`
CuidaPetWeb -> Views -> `Especialidade` -> `Edit.cs`
CuidaPetWeb -> Views -> `Especialidade` -> `Delete.cs`
CuidaPetWeb -> Views -> `Especialidade` -> `Details.cs`
Service -> `EspecialidadeService.cs`
> realiza implementação de CRUD para caso de uso Manter Especialidade

- Codigo/Core/DTO/NotificacaoDto.cs
- Codigo/Core/Service/INotificacaoService.cs
- Codigo/CuidaPetWeb/Controllers/NotificacaoController.cs
- Codigo/CuidaPetWeb/Mappers/NotificacaoProfile.cs
- Codigo/CuidaPetWeb/Models/NotificacaoViewModel.cs
- Codigo/CuidaPetWeb/Program.cs
- Codigo/Service/NotificacaoService.cs
Implementado o caso de uso com os métodos necessários para a utilização por outras classes.
Close #193
> Implementado caso de uso Receber Notificações

- Codigo/CuidaPetWeb/Controllers/FuncionarioController.cs
- Codigo/CuidaPetWeb/Mappers/FuncionarioProfile.cs
- Codigo/CuidaPetWeb/Views/Funcionario/Create.cshtml
- Codigo/CuidaPetWeb/Views/Funcionario/Delete.cshtml
- Codigo/CuidaPetWeb/Views/Funcionario/Details.cshtml
- Codigo/CuidaPetWeb/Views/Funcionario/Edit.cshtml
- Codigo/CuidaPetWeb/Views/Funcionario/Index.cshtml
> Criar view baseado no design system do caso de uso "Manter Funcionários

- Codigo/CuidaPetWeb/Controllers/ConsultarEstabelecimentosController.cs
- Codigo/CuidaPetWeb/Controllers/ConsultarItensController.cs
- Codigo/CuidaPetWeb/Mappers/ConsultarEstabelecimentosProfile.cs
- Codigo/CuidaPetWeb/Mappers/ProdutoProfile.cs
- Codigo/CuidaPetWeb/Models/ConsultarEstabelecimentosViewModel.cs
- Codigo/CuidaPetWeb/Models/ConsultarItensViewModel.cs
- Codigo/CuidaPetWeb/Models/DetalhesEstabelecimentoViewModel.cs
- Codigo/CuidaPetWeb/Models/ProdutoViewModel.cs
- Codigo/CuidaPetWeb/Views/ConsultarEstabelecimentos/Details.cshtml
- Codigo/CuidaPetWeb/Views/ConsultarEstabelecimentos/Index.cshtml
- Codigo/CuidaPetWeb/Views/ConsultarItens/Index.cshtml
- Codigo/CuidaPetWeb/Views/Shared/_Layout.cshtml
- Consultar estabelecimentos.
- Consultar itens.
- Consultar itens dentro de cada estabelecimento.
> Implementar Caso de Uso "Consultar Estabelecimentos"

- Codigo/Core/DTO/RacaDto.cs
- Codigo/Core/DTO/VacinacaoDto.cs
- Codigo/Core/Service/IVacinacaoService.cs
- Codigo/CuidaPetWeb/Controllers/VacinacaoController.cs
- Codigo/CuidaPetWeb/Mappers/VacinacaoProfile.cs
- Codigo/CuidaPetWeb/Models/VacinacaoViewModel.cs
- Codigo/CuidaPetWeb/Program.cs
- Codigo/Service/VacinacaoService.cs
Feito as controllers e services do caso de uso "Vacinar Pet"
> Add: caso de uso Vacinar Pet

- Codigo/Core/Service/INotificacaoService.cs
- Codigo/CuidaPetWeb/Controllers/NotificacaoController.cs
- Codigo/CuidaPetWeb/Views/Shared/_Layout.cshtml
- Codigo/CuidaPetWeb/wwwroot/css/site.css
- Codigo/CuidaPetWeb/wwwroot/js/site.js
- Codigo/CuidaPetWebTests/Controllers/NotificacaoControllerTests.cs
- Codigo/Service/NotificacaoService.cs
Tela desktop:
Tela móvel:
Close #195
> Add view para Notificacao
